language: objective-c
osx_image: xcode8.2
cache: false
sudo: false
rvm:
  - 2.3.3
before_install:
  - gem install bundler
  - bundle install --without=documentation
  - bundle exec pod install --repo-update
script:
  - set -o pipefail && xcodebuild test -workspace SwipeToReveal.xcworkspace -scheme 'SwipeToReveal Tests' -destination 'id=34FA4749-C467-4D45-9F8E-E31AEDDC39C2' ONLY_ACTIVE_ARCH=NO | xcpretty
  - set -o pipefail && xcodebuild test -workspace SwipeToReveal.xcworkspace -scheme 'SwipeToReveal Example Tests' -destination 'id=34FA4749-C467-4D45-9F8E-E31AEDDC39C2' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
